name: Hugo

on: 
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: 'true'

    - name: create worktree
      run: git worktree add -B gh-pages public origin/gh-pages

    - name: Hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ubuntu

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: cengique/lectures-prog-data-analysis
        ref: gh-pages-sp21
        path: public/sp21
        submodules: 'true'

    - name: Remove git
      run: rm -rf public/sp21/.git

    - name: Checkout
      uses: actions/checkout@v2
      with:
        repository: cengique/lectures-prog-data-analysis
        ref: gh-pages-sp22
        path: public/sp22
        submodules: 'true'

    - name: Remove git
      run: rm -rf public/sp22/.git

    - name: Push
      run: chmod 755 ./deploy.sh && ./deploy.sh
